import type { Question } from "./curriculum"
import { grade3MathExtraQuestions } from "./grade3_math_extra_questions"

// Additional questions merged with each topic's base questions to create a
// larger pool. Quizzes then draw a random subset, so attempts vary.
// Key format: `${gradeId}:${subjectId}:${topicId}`
export const extraQuestions: Record<string, Question[]> = {
  // ---------------------------------------------------------------- Grade 3 Math
  "grade-3:math:numbers": [
    {
      id: "e1",
      type: "mcq",
      prompt: "What is the value of the digit 7 in 471?",
      options: ["7", "70", "700", "47"],
      answerIndex: 1,
      explanation: "The 7 is in the tens place, so its value is 70.",
    },
    {
      id: "e2",
      type: "number",
      prompt: "What is 400 + 50 + 9?",
      answer: 459,
      explanation: "Add the place values: 400 + 50 + 9 = 459.",
    },
    {
      id: "e3",
      type: "boolean",
      prompt: "620 is greater than 602.",
      answer: true,
      explanation: "Both start with 6, but 620 has 2 tens vs 0 tens, so it is larger.",
    },
    {
      id: "e4",
      type: "mcq",
      prompt: "Which of these is an even number?",
      options: ["7", "13", "24", "31"],
      answerIndex: 2,
      explanation: "24 ends in 4, so it is even.",
    },
    {
      id: "e5",
      type: "number",
      prompt: "What number comes just before 500?",
      answer: 499,
      explanation: "One less than 500 is 499.",
    },
  ],
  "grade-3:math:addition": [
    {
      id: "e1",
      type: "number",
      prompt: "What is 45 + 27?",
      answer: 72,
      explanation: "40 + 20 = 60 and 5 + 7 = 12, so 60 + 12 = 72.",
    },
    { id: "e2", type: "number", prompt: "What is 9 + 9?", answer: 18, explanation: "9 + 9 = 18." },
    {
      id: "e3",
      type: "mcq",
      prompt: "Which sum equals 50?",
      options: ["20 + 30", "40 + 20", "25 + 20", "35 + 10"],
      answerIndex: 0,
      explanation: "20 + 30 = 50.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "0 + 8 equals 8.",
      answer: true,
      explanation: "Adding zero does not change a number.",
    },
    {
      id: "e5",
      type: "number",
      prompt: "What is 123 + 100?",
      answer: 223,
      explanation: "Add 100 to the hundreds: 123 + 100 = 223.",
    },
  ],
  "grade-3:math:subtraction": [
    { id: "e1", type: "number", prompt: "What is 90 - 35?", answer: 55, explanation: "90 - 35 = 55." },
    {
      id: "e2",
      type: "number",
      prompt: "What is 12 - 12?",
      answer: 0,
      explanation: "Taking away everything leaves 0.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "What is 45 - 20?",
      options: ["25", "20", "35", "15"],
      answerIndex: 0,
      explanation: "45 - 20 = 25.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "100 - 1 equals 99.",
      answer: true,
      explanation: "One less than 100 is 99.",
    },
    { id: "e5", type: "number", prompt: "What is 64 - 9?", answer: 55, explanation: "64 - 9 = 55." },
  ],
  "grade-3:math:multiplication": [
    { id: "e1", type: "number", prompt: "What is 4 × 4?", answer: 16, explanation: "4 × 4 = 16." },
    { id: "e2", type: "number", prompt: "What is 8 × 3?", answer: 24, explanation: "8 × 3 = 24." },
    {
      id: "e3",
      type: "mcq",
      prompt: "What is 5 × 0?",
      options: ["5", "0", "50", "10"],
      answerIndex: 1,
      explanation: "Any number times 0 is 0.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "6 × 2 gives the same answer as 2 × 6.",
      answer: true,
      explanation: "Order does not change the product. Both equal 12.",
    },
    { id: "e5", type: "number", prompt: "What is 9 × 3?", answer: 27, explanation: "9 × 3 = 27." },
  ],
  "grade-3:math:division": [
    { id: "e1", type: "number", prompt: "What is 16 ÷ 4?", answer: 4, explanation: "16 ÷ 4 = 4." },
    { id: "e2", type: "number", prompt: "What is 18 ÷ 2?", answer: 9, explanation: "18 ÷ 2 = 9." },
    {
      id: "e3",
      type: "mcq",
      prompt: "What is 24 ÷ 6?",
      options: ["3", "4", "5", "6"],
      answerIndex: 1,
      explanation: "24 ÷ 6 = 4.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "10 ÷ 1 equals 10.",
      answer: true,
      explanation: "Dividing by 1 does not change a number.",
    },
    { id: "e5", type: "number", prompt: "What is 21 ÷ 3?", answer: 7, explanation: "21 ÷ 3 = 7." },
  ],
  "grade-3:math:fractions": [
    {
      id: "e1",
      type: "mcq",
      prompt: "Half of a pizza is written as:",
      options: ["1/2", "1/3", "1/4", "1/8"],
      answerIndex: 0,
      explanation: "One of two equal parts is 1/2.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "1/3 is smaller than 1/2.",
      answer: true,
      explanation: "Thirds are smaller pieces than halves.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "2/4 is the same as which fraction?",
      options: ["1/2", "1/4", "1/3", "3/4"],
      answerIndex: 0,
      explanation: "2/4 simplifies to 1/2.",
    },
    {
      id: "e4",
      type: "number",
      prompt: "How many thirds make one whole? Type the number.",
      answer: 3,
      explanation: "Three thirds (3/3) make one whole.",
    },
    {
      id: "e5",
      type: "boolean",
      prompt: "The top number of a fraction is called the numerator.",
      answer: true,
      explanation: "The numerator is on top; the denominator is on the bottom.",
    },
  ],
  "grade-3:math:geometry": [
    {
      id: "e1",
      type: "number",
      prompt: "How many sides does a rectangle have?",
      answer: 4,
      explanation: "A rectangle has 4 sides.",
    },
    {
      id: "e2",
      type: "mcq",
      prompt: "A shape with 6 sides is called a:",
      options: ["Pentagon", "Hexagon", "Square", "Triangle"],
      answerIndex: 1,
      explanation: "A 6-sided shape is a hexagon.",
    },
    {
      id: "e3",
      type: "boolean",
      prompt: "A triangle has 3 corners.",
      answer: true,
      explanation: "A triangle has 3 sides and 3 corners.",
    },
    {
      id: "e4",
      type: "number",
      prompt: "How many corners does a rectangle have?",
      answer: 4,
      explanation: "A rectangle has 4 corners.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "A ball is shaped like a:",
      options: ["Circle", "Sphere", "Square", "Cube"],
      answerIndex: 1,
      explanation: "A ball is a 3D round shape called a sphere.",
    },
  ],

  // ------------------------------------------------------------- Grade 3 Science
  "grade-3:science:living-things": [
    {
      id: "e1",
      type: "mcq",
      prompt: "Which of these grows and needs food?",
      options: ["Car", "Flower", "Rock", "Cup"],
      answerIndex: 1,
      explanation: "A flower is living; it grows and needs water and light.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Fish are living things.",
      answer: true,
      explanation: "Fish move, eat, and grow, so they are living.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "Which is a non-living thing?",
      options: ["Dog", "Cat", "Book", "Bird"],
      answerIndex: 2,
      explanation: "A book does not eat or grow, so it is non-living.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "Living things can have babies (reproduce).",
      answer: true,
      explanation: "Making more of their own kind is something living things do.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "What do living things need to breathe?",
      options: ["Air", "Plastic", "Glass", "Metal"],
      answerIndex: 0,
      explanation: "Living things need air to breathe.",
    },
  ],
  "grade-3:science:plants": [
    {
      id: "e1",
      type: "mcq",
      prompt: "Seeds grow into:",
      options: ["Plants", "Rocks", "Clouds", "Animals"],
      answerIndex: 0,
      explanation: "A seed grows into a new plant.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Flowers can make seeds.",
      answer: true,
      explanation: "Flowers help the plant make new seeds.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "What color are most leaves?",
      options: ["Green", "Blue", "Red", "Black"],
      answerIndex: 0,
      explanation: "Most leaves are green because of a substance that catches light.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "Roots usually grow under the ground.",
      answer: true,
      explanation: "Roots grow down into the soil to reach water.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "Which colorful part of a plant attracts bees?",
      options: ["Flower", "Root", "Stem", "Leaf"],
      answerIndex: 0,
      explanation: "Bright flowers attract bees and other insects.",
    },
  ],
  "grade-3:science:five-senses": [
    {
      id: "e1",
      type: "mcq",
      prompt: "Which sense uses your eyes?",
      options: ["Sight", "Smell", "Taste", "Touch"],
      answerIndex: 0,
      explanation: "You see with your eyes, which is the sense of sight.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "You use your tongue to taste sweet things.",
      answer: true,
      explanation: "The tongue senses taste, like sweet and sour.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "Soft and hard are things you can:",
      options: ["Touch", "See only", "Hear", "Smell"],
      answerIndex: 0,
      explanation: "You feel soft and hard using touch.",
    },
    {
      id: "e4",
      type: "mcq",
      prompt: "A loud drum is sensed with your:",
      options: ["Ears", "Nose", "Tongue", "Skin"],
      answerIndex: 0,
      explanation: "You hear sounds with your ears.",
    },
    {
      id: "e5",
      type: "boolean",
      prompt: "Your nose can smell food cooking.",
      answer: true,
      explanation: "Smelling is the job of your nose.",
    },
  ],
  "grade-3:science:weather": [
    {
      id: "e1",
      type: "mcq",
      prompt: "Frozen rain that falls in winter is called:",
      options: ["Snow", "Dust", "Smoke", "Steam"],
      answerIndex: 0,
      explanation: "Snow is frozen water that falls from clouds.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "A thermometer measures temperature.",
      answer: true,
      explanation: "A thermometer tells us how hot or cold it is.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "On a windy day, what is moving?",
      options: ["Air", "Rocks", "Houses", "Roads"],
      answerIndex: 0,
      explanation: "Wind is moving air.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "A rainbow can appear after rain.",
      answer: true,
      explanation: "Sunlight through raindrops can make a rainbow.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "Which season is usually the coldest?",
      options: ["Winter", "Summer", "Spring", "Fall"],
      answerIndex: 0,
      explanation: "Winter is the coldest season.",
    },
  ],
  "grade-3:science:matter": [
    {
      id: "e1",
      type: "mcq",
      prompt: "Which of these is a gas?",
      options: ["Ice", "Water", "Air", "Rock"],
      answerIndex: 2,
      explanation: "Air is a gas; it spreads to fill space.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Liquids take the shape of their container.",
      answer: true,
      explanation: "A liquid flows and fills the bottom of its container.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "Steam is water in which state?",
      options: ["Solid", "Liquid", "Gas", "Rock"],
      answerIndex: 2,
      explanation: "Steam is water as a gas.",
    },
    {
      id: "e4",
      type: "number",
      prompt: "How many main states of matter are there?",
      answer: 3,
      explanation: "Solid, liquid, and gas make 3 states.",
    },
    {
      id: "e5",
      type: "boolean",
      prompt: "A solid keeps its own shape.",
      answer: true,
      explanation: "Solids hold their shape unless something changes them.",
    },
  ],

  // ----------------------------------------------------------- Grade 3 Geography
  "grade-3:geography:land-water": [
    {
      id: "e1",
      type: "mcq",
      prompt: "A small body of fresh water surrounded by land is a:",
      options: ["Lake", "Ocean", "Sea", "Gulf"],
      answerIndex: 0,
      explanation: "A lake is fresh water surrounded by land.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Ocean water is salty.",
      answer: true,
      explanation: "Oceans are full of salt water.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "Water flowing across land in a channel is a:",
      options: ["River", "Mountain", "Desert", "Forest"],
      answerIndex: 0,
      explanation: "A river carries water across the land.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "An island is land surrounded by water.",
      answer: true,
      explanation: "Water goes all the way around an island.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "Most of Earth's surface is:",
      options: ["Water", "Land", "Ice", "Sand"],
      answerIndex: 0,
      explanation: "About three-quarters of Earth is water.",
    },
  ],
  "grade-3:geography:continents": [
    {
      id: "e1",
      type: "mcq",
      prompt: "Which is the smallest continent?",
      options: ["Australia", "Asia", "Africa", "Europe"],
      answerIndex: 0,
      explanation: "Australia is the smallest continent.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Africa is a continent.",
      answer: true,
      explanation: "Africa is one of the 7 continents.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "Penguins mostly live on which cold continent?",
      options: ["Antarctica", "Africa", "Asia", "Europe"],
      answerIndex: 0,
      explanation: "Many penguins live in icy Antarctica.",
    },
    {
      id: "e4",
      type: "number",
      prompt: "How many continents are there?",
      answer: 7,
      explanation: "Earth has 7 continents.",
    },
    {
      id: "e5",
      type: "boolean",
      prompt: "Europe and Asia are both continents.",
      answer: true,
      explanation: "Both Europe and Asia are separate continents.",
    },
  ],
  "grade-3:geography:maps": [
    {
      id: "e1",
      type: "mcq",
      prompt: "The direction opposite of East is:",
      options: ["West", "North", "South", "Up"],
      answerIndex: 0,
      explanation: "West is opposite East.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "A globe is a round model of Earth.",
      answer: true,
      explanation: "A globe shows Earth as a sphere.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "The key (legend) on a map explains the:",
      options: ["Symbols", "Weather", "Food", "Music"],
      answerIndex: 0,
      explanation: "A map key tells what the symbols mean.",
    },
    {
      id: "e4",
      type: "mcq",
      prompt: "The direction between North and East is:",
      options: ["Northeast", "Southwest", "Down", "Up"],
      answerIndex: 0,
      explanation: "Between North and East is Northeast.",
    },
    {
      id: "e5",
      type: "boolean",
      prompt: "A map helps you find places.",
      answer: true,
      explanation: "Maps show where places are and how to get there.",
    },
  ],
  "grade-3:geography:my-country": [
    {
      id: "e1",
      type: "mcq",
      prompt: "A cloth with colors and patterns that stands for a country is a:",
      options: ["Flag", "Shoe", "Cloud", "Tree"],
      answerIndex: 0,
      explanation: "Each country has its own flag.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Every country has a capital city.",
      answer: true,
      explanation: "The capital is where a country's leaders work.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "All the countries together are on our:",
      options: ["Earth", "Moon", "Sun", "Star"],
      answerIndex: 0,
      explanation: "All countries are on planet Earth.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "A town is smaller than a country.",
      answer: true,
      explanation: "A country contains many towns and cities.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "People who live in a country are called its:",
      options: ["Citizens", "Visitors", "Tourists", "Strangers"],
      answerIndex: 0,
      explanation: "People who belong to a country are its citizens.",
    },
  ],

  // ---------------------------------------------------------------- Grade 7 Math
  "grade-7:math:integers": [
    { id: "e1", type: "number", prompt: "What is -3 + (-4)?", answer: -7, explanation: "Two negatives combine: -3 + -4 = -7." },
    { id: "e2", type: "number", prompt: "What is -10 + 4?", answer: -6, explanation: "Start at -10 and move up 4 to -6." },
    {
      id: "e3",
      type: "mcq",
      prompt: "Which number is the greatest?",
      options: ["-2", "-5", "-9", "-100"],
      answerIndex: 0,
      explanation: "-2 is closest to zero, so it is the greatest.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "The opposite of -6 is 6.",
      answer: true,
      explanation: "Opposites are the same distance from 0 on each side.",
    },
    { id: "e5", type: "number", prompt: "What is 5 - (-3)?", answer: 8, explanation: "Subtracting a negative adds: 5 + 3 = 8." },
  ],
  "grade-7:math:fractions": [
    {
      id: "e1",
      type: "mcq",
      prompt: "What is 3/8 + 2/8?",
      options: ["5/8", "5/16", "1/8", "6/8"],
      answerIndex: 0,
      explanation: "Same denominator: add tops. 3 + 2 = 5, so 5/8.",
    },
    { id: "e2", type: "number", prompt: "What is 1/3 of 12?", answer: 4, explanation: "12 ÷ 3 = 4." },
    {
      id: "e3",
      type: "boolean",
      prompt: "2/5 is less than 1/2.",
      answer: true,
      explanation: "2/5 = 0.4 and 1/2 = 0.5, so 2/5 is less.",
    },
    {
      id: "e4",
      type: "mcq",
      prompt: "Simplify 6/9.",
      options: ["2/3", "3/4", "1/2", "6/9"],
      answerIndex: 0,
      explanation: "Divide top and bottom by 3: 6/9 = 2/3.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "What is 3/4 written as a decimal?",
      options: ["0.75", "0.5", "0.34", "0.7"],
      answerIndex: 0,
      explanation: "3 ÷ 4 = 0.75.",
    },
  ],
  "grade-7:math:algebra": [
    { id: "e1", type: "number", prompt: "If x = 3, what is 4x + 2?", answer: 14, explanation: "4 × 3 = 12, then 12 + 2 = 14." },
    {
      id: "e2",
      type: "mcq",
      prompt: "Simplify: 6y - 2y.",
      options: ["4y", "8y", "4", "y4"],
      answerIndex: 0,
      explanation: "Combine like terms: 6y - 2y = 4y.",
    },
    { id: "e3", type: "number", prompt: "If a = 10, what is a ÷ 2?", answer: 5, explanation: "10 ÷ 2 = 5." },
    {
      id: "e4",
      type: "boolean",
      prompt: "3x means 3 times x.",
      answer: true,
      explanation: "A number next to a variable means multiply.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "Which expression means 'twice a number n'?",
      options: ["2n", "n + 2", "n ÷ 2", "n - 2"],
      answerIndex: 0,
      explanation: "'Twice' means two times, so 2n.",
    },
  ],
  "grade-7:math:equations": [
    { id: "e1", type: "number", prompt: "Solve: x ÷ 2 = 6. What is x?", answer: 12, explanation: "Multiply both sides by 2: x = 12." },
    { id: "e2", type: "number", prompt: "Solve: x + 8 = 20. What is x?", answer: 12, explanation: "Subtract 8 from both sides: x = 12." },
    { id: "e3", type: "number", prompt: "Solve: 4x = 20. What is x?", answer: 5, explanation: "Divide both sides by 4: x = 5." },
    {
      id: "e4",
      type: "boolean",
      prompt: "Solving an equation means finding the value of the variable.",
      answer: true,
      explanation: "The goal is to find what the variable equals.",
    },
    { id: "e5", type: "number", prompt: "Solve: 3x - 2 = 10. What is x?", answer: 4, explanation: "Add 2 (3x = 12), then divide by 3: x = 4." },
  ],
  "grade-7:math:geometry": [
    { id: "e1", type: "number", prompt: "What is the perimeter of a square with side 5?", answer: 20, explanation: "4 sides of 5: 4 × 5 = 20." },
    {
      id: "e2",
      type: "mcq",
      prompt: "An angle less than 90° is called:",
      options: ["Acute", "Obtuse", "Right", "Straight"],
      answerIndex: 0,
      explanation: "An acute angle is smaller than 90°.",
    },
    { id: "e3", type: "number", prompt: "What is the area of a rectangle 7 by 3?", answer: 21, explanation: "Area = 7 × 3 = 21." },
    {
      id: "e4",
      type: "boolean",
      prompt: "A square is a special kind of rectangle.",
      answer: true,
      explanation: "A square is a rectangle with all sides equal.",
    },
    { id: "e5", type: "number", prompt: "How many degrees are in a right angle?", answer: 90, explanation: "A right angle is 90°." },
  ],
  "grade-7:math:percentages": [
    { id: "e1", type: "number", prompt: "What is 25% of 40?", answer: 10, explanation: "25% is 1/4, and 40 ÷ 4 = 10." },
    { id: "e2", type: "number", prompt: "What is 50% of 8?", answer: 4, explanation: "50% is half of 8, which is 4." },
    {
      id: "e3",
      type: "mcq",
      prompt: "1/2 written as a percent is:",
      options: ["50%", "25%", "75%", "100%"],
      answerIndex: 0,
      explanation: "One half is 50%.",
    },
    { id: "e4", type: "number", prompt: "What is 20% of 100?", answer: 20, explanation: "20% of 100 is 20.", },
    {
      id: "e5",
      type: "boolean",
      prompt: "100% means all of something.",
      answer: true,
      explanation: "100% is the whole amount.",
    },
  ],

  // ------------------------------------------------------------- Grade 7 Science
  "grade-7:science:cells": [
    {
      id: "e1",
      type: "mcq",
      prompt: "The basic building block of all living things is the:",
      options: ["Cell", "Leaf", "Bone", "Drop"],
      answerIndex: 0,
      explanation: "Cells are the smallest building blocks of life.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "The nucleus holds the cell's instructions (DNA).",
      answer: true,
      explanation: "DNA in the nucleus controls the cell.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "Which part is found only in plant cells?",
      options: ["Chloroplast", "Nucleus", "Membrane", "Cytoplasm"],
      answerIndex: 0,
      explanation: "Chloroplasts are found in plant cells, not animal cells.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "Animal cells have a cell wall.",
      answer: false,
      explanation: "Only plant cells have a stiff cell wall.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "The jelly-like fluid that fills a cell is the:",
      options: ["Cytoplasm", "Nucleus", "Cell wall", "Vacuole"],
      answerIndex: 0,
      explanation: "Cytoplasm fills the space inside the cell.",
    },
  ],
  "grade-7:science:photosynthesis": [
    {
      id: "e1",
      type: "mcq",
      prompt: "The main energy source for photosynthesis is:",
      options: ["Sunlight", "Soil", "Wind", "Rocks"],
      answerIndex: 0,
      explanation: "Sunlight provides the energy for photosynthesis.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Photosynthesis produces oxygen.",
      answer: true,
      explanation: "Plants release oxygen as they make food.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "The green pigment that captures light is:",
      options: ["Chlorophyll", "Keratin", "Melanin", "Starch"],
      answerIndex: 0,
      explanation: "Chlorophyll makes leaves green and captures light.",
    },
    {
      id: "e4",
      type: "mcq",
      prompt: "The sugar a plant makes is used as:",
      options: ["Food", "Rock", "Gas", "Metal"],
      answerIndex: 0,
      explanation: "The sugar is the plant's food (energy).",
    },
    {
      id: "e5",
      type: "boolean",
      prompt: "Photosynthesis happens mostly at night.",
      answer: false,
      explanation: "It needs light, so it happens during the day.",
    },
  ],
  "grade-7:science:forces": [
    {
      id: "e1",
      type: "mcq",
      prompt: "The force that pulls objects toward Earth is:",
      options: ["Gravity", "Friction", "Magnetism", "Tension"],
      answerIndex: 0,
      explanation: "Gravity pulls things down toward Earth.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Friction can slow down moving objects.",
      answer: true,
      explanation: "Friction resists motion and slows things down.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "The unit used to measure force is the:",
      options: ["Newton", "Meter", "Liter", "Gram"],
      answerIndex: 0,
      explanation: "Force is measured in newtons (N).",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "A push and a pull are both forces.",
      answer: true,
      explanation: "Forces can push or pull an object.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "The tendency of an object to keep moving is called:",
      options: ["Inertia", "Gravity", "Heat", "Light"],
      answerIndex: 0,
      explanation: "Inertia keeps objects moving unless a force acts.",
    },
  ],
  "grade-7:science:solar-system": [
    {
      id: "e1",
      type: "number",
      prompt: "How many planets are in our solar system?",
      answer: 8,
      explanation: "There are 8 planets.",
    },
    {
      id: "e2",
      type: "mcq",
      prompt: "Which planet is closest to the Sun?",
      options: ["Mercury", "Earth", "Mars", "Venus"],
      answerIndex: 0,
      explanation: "Mercury is the closest planet to the Sun.",
    },
    {
      id: "e3",
      type: "boolean",
      prompt: "The Sun is a star.",
      answer: true,
      explanation: "The Sun is the star at the center of our solar system.",
    },
    {
      id: "e4",
      type: "mcq",
      prompt: "Which is the largest planet?",
      options: ["Jupiter", "Earth", "Mars", "Saturn"],
      answerIndex: 0,
      explanation: "Jupiter is the biggest planet.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "Which planet is known as the 'Red Planet'?",
      options: ["Mars", "Venus", "Neptune", "Mercury"],
      answerIndex: 0,
      explanation: "Mars looks red because of its rusty soil.",
    },
  ],
  "grade-7:science:matter-changes": [
    {
      id: "e1",
      type: "mcq",
      prompt: "A liquid turning into a gas is called:",
      options: ["Evaporation", "Freezing", "Melting", "Condensation"],
      answerIndex: 0,
      explanation: "Evaporation changes a liquid into a gas.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Melting changes a solid into a liquid.",
      answer: true,
      explanation: "Adding heat melts a solid into a liquid.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "A gas turning into a liquid is called:",
      options: ["Condensation", "Evaporation", "Melting", "Boiling"],
      answerIndex: 0,
      explanation: "Condensation changes a gas into a liquid.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "Freezing changes a liquid into a solid.",
      answer: true,
      explanation: "Removing heat freezes a liquid into a solid.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "Which of these is a physical change?",
      options: ["Melting ice", "Burning wood", "Rusting iron", "Baking a cake"],
      answerIndex: 0,
      explanation: "Melting ice can be reversed, so it is a physical change.",
    },
  ],

  // ----------------------------------------------------------- Grade 7 Geography
  "grade-7:geography:continents-oceans": [
    {
      id: "e1",
      type: "number",
      prompt: "How many oceans does Earth have?",
      answer: 5,
      explanation: "Earth has 5 oceans.",
    },
    {
      id: "e2",
      type: "mcq",
      prompt: "Which is the largest ocean?",
      options: ["Pacific", "Atlantic", "Indian", "Arctic"],
      answerIndex: 0,
      explanation: "The Pacific is the largest ocean.",
    },
    {
      id: "e3",
      type: "boolean",
      prompt: "The Atlantic Ocean lies between the Americas and Europe/Africa.",
      answer: true,
      explanation: "The Atlantic separates those continents.",
    },
    {
      id: "e4",
      type: "mcq",
      prompt: "Which is the largest continent?",
      options: ["Asia", "Africa", "Europe", "Antarctica"],
      answerIndex: 0,
      explanation: "Asia is the largest continent.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "Which is the smallest ocean?",
      options: ["Arctic", "Pacific", "Indian", "Atlantic"],
      answerIndex: 0,
      explanation: "The Arctic Ocean is the smallest.",
    },
  ],
  "grade-7:geography:climate": [
    {
      id: "e1",
      type: "mcq",
      prompt: "A hot, wet climate near the equator is called:",
      options: ["Tropical", "Polar", "Desert", "Temperate"],
      answerIndex: 0,
      explanation: "Areas near the equator have a tropical climate.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Polar regions are very cold.",
      answer: true,
      explanation: "The polar climate is freezing most of the year.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "A very dry climate with little rain is a:",
      options: ["Desert", "Tropical", "Polar", "Coastal"],
      answerIndex: 0,
      explanation: "Deserts get very little rainfall.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "Climate is the usual weather of a place over many years.",
      answer: true,
      explanation: "Climate is the long-term pattern of weather.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "Which climate is the coldest?",
      options: ["Polar", "Tropical", "Temperate", "Desert"],
      answerIndex: 0,
      explanation: "The polar climate is the coldest.",
    },
  ],
  "grade-7:geography:landforms": [
    {
      id: "e1",
      type: "mcq",
      prompt: "A very tall landform with steep sides is a:",
      options: ["Mountain", "Valley", "Plain", "River"],
      answerIndex: 0,
      explanation: "A mountain rises high above the land around it.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "A valley is a low area between hills or mountains.",
      answer: true,
      explanation: "Valleys are the low land between higher ground.",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "A flat, wide area of land is a:",
      options: ["Plain", "Mountain", "Peak", "Cliff"],
      answerIndex: 0,
      explanation: "Plains are large flat areas.",
    },
    {
      id: "e4",
      type: "mcq",
      prompt: "Land surrounded by water on all sides is an:",
      options: ["Island", "Peninsula", "Valley", "Plateau"],
      answerIndex: 0,
      explanation: "An island has water all around it.",
    },
    {
      id: "e5",
      type: "boolean",
      prompt: "A plateau is a raised area of flat land.",
      answer: true,
      explanation: "A plateau is high, flat ground.",
    },
  ],
  "grade-7:geography:maps-latitude": [
    {
      id: "e1",
      type: "mcq",
      prompt: "The line at 0° latitude is the:",
      options: ["Equator", "Prime Meridian", "Tropic", "Pole"],
      answerIndex: 0,
      explanation: "0° latitude is the equator.",
    },
    {
      id: "e2",
      type: "boolean",
      prompt: "Lines of longitude run north to south.",
      answer: true,
      explanation: "Longitude lines run from pole to pole (north-south).",
    },
    {
      id: "e3",
      type: "mcq",
      prompt: "The North Pole is at what latitude?",
      options: ["90°N", "0°", "45°S", "180°"],
      answerIndex: 0,
      explanation: "The North Pole is at 90° North.",
    },
    {
      id: "e4",
      type: "boolean",
      prompt: "The equator is the longest line of latitude.",
      answer: true,
      explanation: "The equator is the widest point around Earth.",
    },
    {
      id: "e5",
      type: "mcq",
      prompt: "The line at 0° longitude is called the:",
      options: ["Prime Meridian", "Equator", "Tropic", "Date Line"],
      answerIndex: 0,
      explanation: "0° longitude is the Prime Meridian.",
    },
  ],
  ...grade3MathExtraQuestions,
}

export function getExtraQuestions(
  gradeId: string,
  subjectId: string,
  topicId: string,
): Question[] {
  return extraQuestions[`${gradeId}:${subjectId}:${topicId}`] ?? []
}
